services:
  nginx:
    restart: always
    container_name: nginx_app
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro